name: test-all
on:
  push:
    branches:
      - develop
  pull_request:
    types: [opened, reopened, synchronize]
jobs:
  test-all:
    name: Test All
    runs-on: ubuntu-latest
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v4
      with:
        path: src/github.com/${{ github.repository }}
        fetch-depth: 0
    - name: Set Up Go
      uses: actions/setup-go@v5
      with:
        go-version-file: src/github.com/${{ github.repository }}/go.mod
        check-latest: true
    - name: Run Tests
      run: |
        set -e -x
        export GOPATH=$(pwd)
        cd src/github.com/${{ github.repository }}
        ./hack/build.sh
        ./hack/test-all.sh
        ./hack/build-binaries.sh
